"""Neo4j connection and query helper for the Veritas-Medica knowledge graph.

This module is the deterministic query path required by CLAUDE.md Principle 1:
clinical facts, procedure/service codes, and NPHIES necessity decisions are
resolved by Cypher against the graph — never generated by an LLM.

Configuration comes from the environment:
    NEO4J_URI   (required)  e.g. bolt://localhost:7687 or neo4j://host:7687
    NEO4J_AUTH  (required)  "<user>/<password>", the Neo4j docker convention
    NEO4J_DATABASE (optional) defaults to "neo4j"
"""
from __future__ import annotations

import os
from typing import Any, Iterable, Optional

DEFAULT_URI = "bolt://localhost:7687"
DEFAULT_DATABASE = "neo4j"


class GraphError(RuntimeError):
    """Raised when the graph connection or query cannot be completed."""


def parse_auth(raw: Optional[str]) -> tuple[str, str]:
    """Parse NEO4J_AUTH ("user/password") into a (user, password) tuple.

    The password may itself contain "/", so only the first separator splits.
    """
    if not raw or "/" not in raw:
        raise GraphError(
            'NEO4J_AUTH must be set as "<user>/<password>" (e.g. "neo4j/password").'
        )
    user, _, password = raw.partition("/")
    if not user or not password:
        raise GraphError('NEO4J_AUTH must be "<user>/<password>" with both parts set.')
    return user, password


class GraphClient:
    """Thin wrapper over the Neo4j driver.

    The driver is imported and constructed lazily so this module can be
    imported (and unit-tested with a fake session) without a live database or
    the neo4j package installed.
    """

    def __init__(
        self,
        uri: Optional[str] = None,
        auth: Optional[str] = None,
        database: Optional[str] = None,
    ) -> None:
        self._uri = uri or os.environ.get("NEO4J_URI", DEFAULT_URI)
        self._auth_raw = auth if auth is not None else os.environ.get("NEO4J_AUTH")
        self._database = database or os.environ.get("NEO4J_DATABASE", DEFAULT_DATABASE)
        self._driver: Any = None

    # -- lifecycle ---------------------------------------------------------
    def connect(self) -> Any:
        if self._driver is not None:
            return self._driver
        try:
            from neo4j import GraphDatabase  # imported lazily on purpose
        except ImportError as exc:  # pragma: no cover - env-dependent
            raise GraphError(
                "The 'neo4j' package is required to connect. Install it with "
                "`uv pip install neo4j`."
            ) from exc
        user, password = parse_auth(self._auth_raw)
        try:
            self._driver = GraphDatabase.driver(self._uri, auth=(user, password))
        except Exception as exc:  # pragma: no cover - env-dependent
            raise GraphError(f"Could not open Neo4j driver for {self._uri}: {exc}") from exc
        return self._driver

    def close(self) -> None:
        if self._driver is not None:
            self._driver.close()
            self._driver = None

    def __enter__(self) -> "GraphClient":
        self.connect()
        return self

    def __exit__(self, *exc_info: Any) -> None:
        self.close()

    # -- queries -----------------------------------------------------------
    def run(self, cypher: str, **params: Any) -> list[dict[str, Any]]:
        """Execute a Cypher statement and return records as plain dicts."""
        driver = self.connect()
        try:
            with driver.session(database=self._database) as session:
                result = session.run(cypher, **params)
                return [dict(record) for record in result]
        except GraphError:
            raise
        except Exception as exc:
            raise GraphError(f"Cypher execution failed: {exc}") from exc

    def write_many(self, cypher: str, rows: Iterable[dict[str, Any]]) -> int:
        """Run a write statement once per row; returns the number applied."""
        driver = self.connect()
        applied = 0
        try:
            with driver.session(database=self._database) as session:
                for row in rows:
                    session.run(cypher, **row)
                    applied += 1
        except Exception as exc:
            raise GraphError(f"Cypher write failed: {exc}") from exc
        return applied


def get_client() -> GraphClient:
    """Build a GraphClient from the environment."""
    return GraphClient()
