/**
 * Clinical trigger vocabulary -- GENERATED. Do not edit by hand:
 *   python tools/build_clinical_vocabulary.py
 *
 * Sources (retrieved 2026-09-18, kept under docs/reference/clinical-vocabulary/):
 *   * DICOM PS3.16 CID 29 Acquisition Modality -- all 24 entries, meanings verbatim.
 *   * LOINC Top 2000+ Lab Observations v1.6 (NIH/LHNCBC) -- analytes in rank order up to
 *     rank 500; rank decides inclusion, not preference.
 * Everything else lives in the generator's curated block, which expands only to terms that
 * already appear in those two files (ALT -> alanine aminotransferase, CBC -> complete blood
 * count), so every entry is checkable.
 *
 * This is a trigger vocabulary, not clinical content: the labels it feeds are tasks to
 * carry out, never findings, and a row is only ever offered when the clinician's own words
 * contain one of these terms.
 */

/** DICOM modality meanings, as typed by clinicians (50 phrases). */
export const IMAGING_KEYWORDS: readonly string[] = [
  "autorefraction",
  "barium study",
  "biomagnetic imaging",
  "cat scan",
  "colonoscopy",
  "computed radiography",
  "computed tomography",
  "ct scan",
  "dental x-ray",
  "diaphanography",
  "digital radiography",
  "digital x-ray",
  "endoscopy",
  "external-camera photography",
  "fluoroscopy",
  "gastroscopy",
  "general microscopy",
  "intra-oral radiography",
  "laser surface scan",
  "magnetic resonance",
  "magnetic resonance imaging",
  "mammogram",
  "mammography",
  "mr scan",
  "mri",
  "nuclear medicine",
  "nuclear scan",
  "opg",
  "ophthalmic photography",
  "panoramic x-ray",
  "pet scan",
  "pet-ct",
  "photoacoustic",
  "plain film",
  "positron emission tomography",
  "radiofluoroscopy",
  "radiograph",
  "radiographic imaging",
  "scintigraphy",
  "slide microscopy",
  "sonogram",
  "sonography",
  "thermography",
  "ultrasound",
  "visual acuity",
  "x-ray",
  "xray",
];

/** Analytes and panels (465 phrases). */
export const LAB_KEYWORDS: readonly string[] = [
  "25-hydroxyvitamin d",
  "a1c",
  "abg",
  "abo & rh group",
  "abo group",
  "acetaminophen",
  "acetone",
  "activated clotting time",
  "activated partial thromboplastin time",
  "afp",
  "alanine aminotransferase",
  "alb",
  "albumin",
  "albumin/globulin",
  "alkaline phosphatase",
  "alp",
  "alpha 1 globulin",
  "alpha 2 globulin",
  "alpha fetoprotein",
  "alpha-1-fetoprotein",
  "alt",
  "amikacin",
  "ammonia",
  "amorphous sediment",
  "amphetamines",
  "ampicillin",
  "ampicillin+sulbactam",
  "amy",
  "amylase",
  "anion gap",
  "anion gap 3",
  "anion gap 4",
  "anisocytosis",
  "anti-hcv",
  "appearance of urine",
  "aptt",
  "aspartate aminotransferase",
  "ast",
  "aztreonam",
  "b12",
  "bacteria",
  "bacteria identified",
  "barbiturates",
  "base deficit",
  "base excess",
  "basophils",
  "basophils/100 leukocytes",
  "benzodiazepines",
  "benzoylecgonine",
  "beta globulin",
  "bicarbonate",
  "bilirubin",
  "bilirubin.direct",
  "bilirubin.indirect",
  "bilirubin.total",
  "biopsy",
  "blood culture",
  "blood gas",
  "blood group antibody screen",
  "blood product disposition",
  "blood product type",
  "blood product unit id",
  "bnp",
  "body temperature",
  "borrelia burgdorferi igg+igm ab",
  "bun",
  "burr cells",
  "c reactive protein",
  "c&s",
  "ca",
  "ca125",
  "ca19-9",
  "calcidiol",
  "calciferol",
  "calcium",
  "calcium.ionized",
  "cancer ag 125",
  "cancer antigen 125",
  "cancer antigen 19-9",
  "cannabinoids",
  "carbon dioxide",
  "carbon dioxide, total",
  "carcinoembryonic ag",
  "casts",
  "cbc",
  "cbc with diff",
  "cd3 cells",
  "cd3 cells/100 cells",
  "cd3+cd4+ cells/100 cells",
  "cd3+cd4+ cells/cd3+cd8+ cells",
  "cd3+cd8+ cells",
  "cd3+cd8+ cells/100 cells",
  "cea",
  "cefazolin",
  "cefepime",
  "cefotaxime",
  "cefotetan",
  "ceftazidime",
  "ceftriaxone",
  "cell fractions/differential",
  "cells counted total",
  "cftr gene mutations found",
  "character of urine",
  "chlamydia trachomatis dna",
  "chlamydia trachomatis rrna",
  "chloride",
  "chol",
  "cholecalciferol",
  "cholesterol",
  "cholesterol non hdl",
  "cholesterol.total/cholesterol",
  "choriogonadotropin",
  "choriogonadotropin.beta subunit",
  "ciprofloxacin",
  "ck",
  "clindamycin",
  "clostridium difficile",
  "clostridium difficile toxin a+b",
  "cobalamin",
  "cocaine",
  "collection duration of urine",
  "color of body fluid",
  "color of cerebral spinal fluid",
  "color of urine",
  "complement c3",
  "complement c4",
  "complete blood count",
  "cortisol",
  "creatine kinase",
  "creatine kinase.mb",
  "creatine kinase.mb/creatine kinase.total",
  "creatinine",
  "creatinine dialysis fluid clearance",
  "creatinine renal clearance predicted",
  "crp",
  "crystals",
  "csf culture",
  "culture",
  "culture and sensitivity",
  "cyclosporine",
  "cytology",
  "d ag",
  "d dimer",
  "d-dimer",
  "dacrocytes",
  "dbil",
  "ddimer",
  "dehydroepiandrosterone sulfate",
  "digoxin",
  "dna double strand ab",
  "egfr",
  "electrolytes",
  "eosinophils",
  "eosinophils/100 leukocytes",
  "epithelial cells",
  "epithelial cells.squamous",
  "epstein barr virus early igm ab",
  "erythrocyte distribution width",
  "erythrocyte mean corpuscular hemoglobin",
  "erythrocyte mean corpuscular volume",
  "erythrocyte morphology finding",
  "erythrocyte sedimentation rate",
  "erythrocytes",
  "erythromycin",
  "esr",
  "esr/crp",
  "estradiol",
  "ethanol",
  "f2 gene p.g20210a",
  "f5 gene mutations found",
  "fasting glucose",
  "fbc",
  "fbs",
  "ferritin",
  "fib",
  "fibrin d-dimer ddu",
  "fibrin d-dimer feu",
  "fibrinogen",
  "fine needle aspirate",
  "fna",
  "folate",
  "follicle stimulating hormone",
  "follitropin",
  "free thyroxine",
  "free triiodothyronine",
  "fsh",
  "ft3",
  "ft4",
  "fungus identified",
  "gamma globulin",
  "gamma glutamyl transferase",
  "gentamicin",
  "gfr",
  "ggt",
  "globulin",
  "glomerular filtration",
  "glucose",
  "glucose mean value",
  "glucose tolerance",
  "hb",
  "hba1c",
  "hbsag",
  "hct",
  "hdl",
  "hdl cholesterol",
  "helicobacter pylori",
  "helicobacter pylori igg ab",
  "hematocrit",
  "hemoglobin",
  "hemoglobin a1c",
  "hemoglobin a1c/hemoglobin.total",
  "hemoglobin s",
  "hemoglobin.gastrointestinal",
  "hepatitis",
  "hepatitis a virus igm ab",
  "hepatitis b surface antigen",
  "hepatitis b virus core ab",
  "hepatitis b virus core igm ab",
  "hepatitis b virus surface ab",
  "hepatitis b virus surface ag",
  "hepatitis c antibody",
  "hepatitis c virus ab",
  "hepatitis c virus ab signal/cutoff",
  "herpes simplex virus 2 igg ab",
  "hgb",
  "histopathology",
  "histoplasma capsulatum ag",
  "hiv",
  "hiv 1+2 ab",
  "hiv 1+o+2 ab",
  "homocysteine",
  "hs-crp",
  "human immunodeficiency virus",
  "hyaline casts",
  "hypochromia",
  "imipenem",
  "inhaled oxygen concentration",
  "inhaled oxygen flow rate",
  "inr",
  "insulin",
  "international normalized ratio",
  "iron",
  "iron binding capacity",
  "iron binding capacity.unsaturated",
  "iron saturation",
  "iron/iron binding capacity.total",
  "ketones",
  "kft",
  "kidney function",
  "lactate",
  "lactate dehydrogenase",
  "ldh",
  "ldl",
  "ldl cholesterol",
  "lead",
  "leukocyte esterase",
  "leukocyte morphology finding",
  "leukocytes",
  "leukocytes left shift",
  "levofloxacin",
  "lft",
  "lfts",
  "lh",
  "lip",
  "lipase",
  "lipid",
  "liver function",
  "liver function panel",
  "lutropin",
  "lymphocytes",
  "lymphocytes variant/100 leukocytes",
  "lymphocytes/100 leukocytes",
  "macrocytes",
  "magnesium",
  "major crossmatch",
  "mch",
  "mcs",
  "mcv",
  "measles virus ag",
  "meropenem",
  "metamyelocytes",
  "metamyelocytes/100 leukocytes",
  "methadone",
  "mg",
  "microalbumin",
  "microalbumin ug/min",
  "microalbumin/creatinine",
  "microcytes",
  "microscopic exam",
  "microscopic observation",
  "monocytes",
  "monocytes/100 leukocytes",
  "morphology",
  "mucus",
  "mycobacterium sp identified",
  "myelocytes/100 leukocytes",
  "myoglobin",
  "natriuretic peptide",
  "natriuretic peptide b",
  "neisseria gonorrhoeae dna",
  "neisseria gonorrhoeae rrna",
  "neutrophils",
  "neutrophils.band form",
  "neutrophils.band form/100 leukocytes",
  "neutrophils.segmented/100 leukocytes",
  "neutrophils/100 leukocytes",
  "nitrite",
  "nitrofurantoin",
  "nuclear ab",
  "nuclear ab pattern",
  "nucleated erythrocytes/100 leukocytes",
  "occult blood",
  "ogtt",
  "opiates",
  "osmolality of serum or plasma",
  "other antibiotic",
  "ova+parasites identified",
  "ovalocytes",
  "oxacillin",
  "oxygen",
  "oxygen saturation",
  "oxygen/inspired gas setting",
  "pap smear",
  "parathyrin",
  "parathyrin.intact",
  "partial thromboplastin time",
  "pathologist name",
  "pathology report comments",
  "pathology report final diagnosis",
  "pathology report gross observation",
  "pathology report relevant history",
  "pathology report site of origin",
  "pathology report supplemental reports",
  "pcr",
  "pct",
  "pcv",
  "penicillin",
  "ph of arterial blood",
  "ph of blood",
  "ph of serum or plasma",
  "ph of urine",
  "phencyclidine",
  "phenytoin",
  "phosphate",
  "piperacillin",
  "piperacillin+tazobactam",
  "platelet mean volume",
  "platelet morphology finding",
  "platelets",
  "plt",
  "po4",
  "poikilocytosis",
  "polychromasia",
  "polymerase chain reaction",
  "polymorphonuclear cells/100 leukocytes",
  "potassium",
  "prealbumin",
  "procalcitonin",
  "progesterone",
  "prolactin",
  "prostate specific ag",
  "protein",
  "protein fractions",
  "protein.monoclonal",
  "prothrombin time",
  "psa",
  "pt",
  "pth",
  "ptt",
  "rbc",
  "rbs",
  "rdw",
  "reagin ab",
  "recommended follow-up",
  "reference lab test name",
  "reference lab test results",
  "renal function",
  "retic",
  "reticulocytes",
  "reticulocytes/100 erythrocytes",
  "rft",
  "rheumatoid factor",
  "rubella virus igg ab",
  "salicylates",
  "schistocytes",
  "serology",
  "sgot",
  "sgpt",
  "sirolimus",
  "sodium",
  "specific gravity of urine",
  "specimen source",
  "spo2",
  "sputum culture",
  "statement of adequacy",
  "stool analysis",
  "stool culture",
  "streptococcus agalactiae",
  "streptococcus pyogenes ag",
  "streptococcus.beta-hemolytic",
  "surgical pathology study",
  "tacrolimus",
  "target cells",
  "tbil",
  "testosterone",
  "testosterone free",
  "tetracycline",
  "tetrahydrocannabinol",
  "tft",
  "tg",
  "thyroglobulin ab",
  "thyroid function",
  "thyroperoxidase ab",
  "thyrotropin",
  "thyroxine",
  "thyroxine free",
  "thyroxine free index",
  "tibc",
  "tissue transglutaminase iga ab",
  "tobramycin",
  "toxic granules",
  "transitional cells",
  "treponema pallidum",
  "tricyclic antidepressants",
  "triglyceride",
  "triglycerides",
  "triiodothyronine",
  "triiodothyronine free",
  "triiodothyronine resin uptake",
  "trimethoprim+sulfamethoxazole",
  "trop",
  "troponin",
  "troponin i.cardiac",
  "troponin t.cardiac",
  "tsh",
  "u&e",
  "ua",
  "ua dipstick",
  "ue",
  "unidentified crystals",
  "urate",
  "urate crystals amorphous",
  "urea nitrogen",
  "urea nitrogen/creatinine",
  "uric acid",
  "urinalysis",
  "urine analysis",
  "urine culture",
  "urine mcs",
  "urine sediment comments",
  "urobilinogen",
  "valproate",
  "vancomycin",
  "varicella zoster virus igg ab",
  "vbg",
  "vdrl",
  "vitamin d",
  "vitamin d+metabolites",
  "vitd",
  "volume of 24 hour urine",
  "wbc",
  "wound culture",
  "wound swab",
  "xxx microorganism dna",
  "yeast",
];
