/**
 * Clinical trigger vocabulary -- GENERATED. Do not edit by hand:
 *   python tools/build_clinical_vocabulary.py
 *
 * Sources (retrieved 2026-09-18, kept under docs/reference/clinical-vocabulary/):
 *   * DICOM PS3.16 CID 29 Acquisition Modality -- all 24 entries, meanings verbatim.
 *   * LOINC Top 2000+ Lab Observations v1.6 (NIH/LHNCBC) -- analytes in rank order up to
 *     rank 150; rank decides inclusion, not preference.
 * Everything else lives in the generator's curated block, which expands only to terms that
 * already appear in those two files (ALT -> alanine aminotransferase, CBC -> complete blood
 * count), so every entry is checkable.
 *
 * This is a trigger vocabulary, not clinical content: the labels it feeds are tasks to
 * carry out, never findings, and a row is only ever offered when the clinician's own words
 * contain one of these terms.
 */

/** DICOM modality meanings, as typed by clinicians (50 phrases). */
export const IMAGING_KEYWORDS: readonly string[] = [
  "autorefraction",
  "barium study",
  "biomagnetic imaging",
  "cat scan",
  "colonoscopy",
  "computed radiography",
  "computed tomography",
  "ct scan",
  "dental x-ray",
  "diaphanography",
  "digital radiography",
  "digital x-ray",
  "endoscopy",
  "external-camera photography",
  "fluoroscopy",
  "gastroscopy",
  "general microscopy",
  "intra-oral radiography",
  "laser surface scan",
  "magnetic resonance",
  "magnetic resonance imaging",
  "mammogram",
  "mammography",
  "mr scan",
  "mri",
  "nuclear medicine",
  "nuclear scan",
  "opg",
  "ophthalmic photography",
  "panoramic x-ray",
  "pet scan",
  "pet-ct",
  "photoacoustic",
  "plain film",
  "positron emission tomography",
  "radiofluoroscopy",
  "radiograph",
  "radiographic imaging",
  "scintigraphy",
  "slide microscopy",
  "sonogram",
  "sonography",
  "thermography",
  "ultrasound",
  "visual acuity",
  "x-ray",
  "xray",
];

/** Analytes and panels (167 phrases). */
export const LAB_KEYWORDS: readonly string[] = [
  "25-hydroxyvitamin d",
  "a1c",
  "abg",
  "activated partial thromboplastin time",
  "alanine aminotransferase",
  "albumin",
  "albumin/globulin",
  "alkaline phosphatase",
  "alp",
  "alt",
  "anion gap",
  "anion gap 3",
  "appearance of urine",
  "aptt",
  "aspartate aminotransferase",
  "ast",
  "b12",
  "bacteria",
  "bacteria identified",
  "base excess",
  "basophils",
  "basophils/100 leukocytes",
  "bicarbonate",
  "bilirubin",
  "bilirubin.direct",
  "bilirubin.indirect",
  "bilirubin.total",
  "blood gas",
  "blood product disposition",
  "body temperature",
  "bun",
  "c reactive protein",
  "calcidiol",
  "calcium",
  "calcium.ionized",
  "carbon dioxide",
  "carbon dioxide, total",
  "cbc",
  "chloride",
  "chol",
  "cholesterol",
  "cholesterol.total/cholesterol",
  "cobalamin",
  "color of urine",
  "complete blood count",
  "creatine kinase",
  "creatine kinase.mb",
  "creatinine",
  "crp",
  "culture and sensitivity",
  "egfr",
  "electrolytes",
  "eosinophils",
  "eosinophils/100 leukocytes",
  "epithelial cells.squamous",
  "erythrocyte distribution width",
  "erythrocyte mean corpuscular hemoglobin",
  "erythrocyte mean corpuscular volume",
  "erythrocyte morphology finding",
  "erythrocyte sedimentation rate",
  "erythrocytes",
  "esr",
  "fbc",
  "fbs",
  "free thyroxine",
  "free triiodothyronine",
  "ft3",
  "ft4",
  "gamma glutamyl transferase",
  "gfr",
  "ggt",
  "globulin",
  "glomerular filtration",
  "glucose",
  "hb",
  "hba1c",
  "hct",
  "hdl",
  "hdl cholesterol",
  "hematocrit",
  "hemoglobin",
  "hemoglobin a1c",
  "hemoglobin a1c/hemoglobin.total",
  "hgb",
  "hypochromia",
  "inr",
  "international normalized ratio",
  "iron",
  "ketones",
  "kft",
  "kidney function",
  "ldl",
  "ldl cholesterol",
  "leukocyte esterase",
  "leukocytes",
  "lft",
  "lfts",
  "lipase",
  "liver function",
  "liver function panel",
  "lymphocytes",
  "lymphocytes/100 leukocytes",
  "macrocytes",
  "magnesium",
  "mch",
  "mcs",
  "mcv",
  "microcytes",
  "monocytes",
  "monocytes/100 leukocytes",
  "morphology",
  "mucus",
  "neutrophils",
  "neutrophils.band form/100 leukocytes",
  "neutrophils/100 leukocytes",
  "nitrite",
  "other antibiotic",
  "oxygen",
  "partial thromboplastin time",
  "pathology report comments",
  "pathology report final diagnosis",
  "pathology report relevant history",
  "pathology report supplemental reports",
  "ph of blood",
  "ph of urine",
  "phosphate",
  "platelet mean volume",
  "platelets",
  "plt",
  "potassium",
  "prostate specific ag",
  "protein",
  "prothrombin time",
  "psa",
  "pt",
  "ptt",
  "rbc",
  "rbs",
  "recommended follow-up",
  "reference lab test results",
  "renal function",
  "rft",
  "sgot",
  "sgpt",
  "sodium",
  "specific gravity of urine",
  "specimen source",
  "statement of adequacy",
  "tft",
  "tg",
  "thyroid function",
  "thyrotropin",
  "thyroxine",
  "thyroxine free",
  "triglyceride",
  "triglycerides",
  "troponin i.cardiac",
  "tsh",
  "u&e",
  "ue",
  "urate",
  "urea nitrogen",
  "urea nitrogen/creatinine",
  "urine culture",
  "urobilinogen",
  "vitd",
  "wbc",
];
